print("Algoritmo do pudim.")
print()
print("1. Bata bem os ovos no liquidificador.")
print("2. Acrescente o leite condensado e o leite, e bata novamente.")
print("3. Derreta o açúcar na panela até ficar moreno, acrescente a água e deixe engrossar.")
print("4. Coloque em uma forma redonda e despeje a massa do pudim por cima.")
print("5. Asse em forno médio por 45 minutos, com a assadeira redonda dentro de uma maior com água.")
print("6. Espete um garfo para ver se está bem assado.")
print("7. Deixe esfriar e desenforme.")
print("8. Bon appetit!")