print("Pseudocódigo mine última fase")
print()
print("Vire à esquerda")
print("Siga em frente")
print("Siga em frente")
print("destruir bloco")
print("colocar bloco(base rochosa)")
print("Vire à esquerda")
print("Siga em frente")
print("colocar bloco à frente(tábuas de carvalho)")
print("Vire à esquerda")
print("Siga em frente")
print("colocar bloco à frente(ferro)")
print("Vire à esquerda")
print("colocar bloco à frente(cascalho)")
print("Vire à esquerda")
print("colocar bloco à frente(tnt)")